### PR TITLE
Set mason_logger to fixed version 0.2.4

### PR DESCRIPTION
**Pull request by rhalff**

### CODE REVIEW

**Comment by bartekpacia** [comment]
What a stupid error, lol.

**Comment by rhalff** [comment]
@bartekpacia I've lowered the version to 0.2.4 which should work.

**Comment by bartekpacia** [comment]
Looks like the best solution will be to just fix the compilation errors.

**Comment by bartekpacia** [comment]
See #1290.

Thanks for contributing anyway!

**Pull request closed without merging**
