### PR TITLE
EnterText TapLocation iOS

### PR DESCRIPTION
**Pull request by Surio89**
Since I had problems inserting a text into a keycloak password field on iOS Emulator, I analyzed the problem and found that a button placed right above the input field was the problem (Toggle Password Visibility Button). 

image

By default for iOS, Patrol clicks on the relative position x:0.9, y:0.9 of the text field to be entered. So at the bottom right of the text field by default. However, in my example there is a button that intercepts pointer input. I have created a possibility to determine the relative position where the click in the text field takes place.

I added an `Offset tapLocation` to `enterText` and `enterTextByIndex` for both NativeAutomators. 

This only affects iOS, because as far as I have seen, android does not simulate a click on a specific position.

### CODE REVIEW

**Review by piotruela — CHANGES_REQUESTED** [review]
Thanks for the input. The code looks good, just update the CHANGELOG and we can proceed with merging the PR.

**Comment by lunaticcoding** [comment]
> Thanks for the input. The code looks good, just update the CHANGELOG and we can proceed with merging the PR.

Done :)

**Review by piotruela — APPROVED** [review]
lgtm

**Comment by lunaticcoding** [comment]
@piotruela somehow the commits made by @Surio89 are now attributed to you :S so he does not show up as a contributor even though he contributed to the project :/ 

Can we do something about that so he shows up as well? Would be important to us.

**Comment by mateuszwojtczak** [comment]
@lunaticcoding that's very unfortunate, let's see what we can do about it

**Comment by mateuszwojtczak** [comment]
@lunaticcoding @Surio89 I think it's because @Surio89 committed changes just as a git author Jannik Neidig and not as Surio89 and Github doesn't know that it's the same person. Look at commits tab at the top of this page and you can see that on the other hand commits made by @lunaticcoding are recognized correctly. When @piotruela squashed and merged, he only committed them, but original authors remained and it should be treated as contributions. Also, @lunaticcoding commits are being seen as his contributions in the official repo's contributors page.

So, what can we do? Maybe we could somehow rewrite the history or let Github know that this git author is actually @Surio89?

**Comment by mateuszwojtczak** [comment]
Also: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user

**Comment by Surio89** [comment]
@mateuszwojtczak I have realized that unfortunately I have been using the wrong email address. I have added this email address as a secondary address to my github account. Now I appear in the list thanks a lot!

**Pull request merged**
