### PR TITLE
Getting started: add docs to be aware of ProGuard

### LINKED ISSUE #1804: Add to docs to be aware of proguard in the Getting started page
### Steps to reproduce

NA

### Actual results

Just add it as a warning

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^2.3.1

### Patrol Doctor output

NA

### Flutter Doctor output

NA

### PR DESCRIPTION
**Pull request by Guillergood**
This PR supersedes #1805

Fixes #1804

See also #1542, which is more general

### CODE REVIEW

**Comment by Guillergood** [comment]
Apologies for the late change, I was busy. Did not know what happened on the other PR 😄

**Comment by mateuszwojtczak** [comment]
It looks good, but to make it fully cover the issue maybe we could add explicit config for Proguard? I mean the lines with `keep` and our class names.
@Guillergood @bartekpacia  WDYT?

**Comment by bartekpacia** [comment]
@mateuszwojtczak I tried writing a ProGuard for Patrol last Friday, [but failed](https://github.com/leancodepl/patrol/issues/1542#issuecomment-1792972677). 

For now, changes from this PR are better than nothing, but saying "just disable ProGuard" won't leave good impression on more advanced readers of our docs.

**Comment by Guillergood** [comment]
@mateuszwojtczak I was not able to overcome the situation. Seems like we are missing something when everything is being obfuscated. 

@bartekpacia I found something curious if you put `testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"` in the `app > build.gradle` (inside of `android > defaultConfig`), try to run the patrol test and then `adb shell pm list instrumentation` you will see other packages `AndroidJUnitRunner` but not `PatrolJUnitRunner`. Maybe is it related to something to ProGuard...

**Comment by Guillergood** [comment]
@mateuszwojtczak I was not able to overcome the situation. Seems like we are missing something when everything is being obfuscated. 

@bartekpacia I found something curious if you put `testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"` in the `app > build.gradle` (inside of `android > defaultConfig`), try to run the patrol test and then `adb shell pm list instrumentation` you will see other packages `AndroidJUnitRunner` but not `PatrolJUnitRunner`. Maybe is it related to something to ProGuard...

**Review by mateuszwojtczak — APPROVED** [review]
LGTM, we'll try to deliver a proper rules file, but for now this warning is fair enough.

**Pull request merged**
