### PR TITLE
Clean up bundled test

### PR DESCRIPTION
**Pull request by bartekpacia**

### CODE REVIEW

**Comment by bartekpacia** [comment]
At the top of `bundled_test.dart` there's `// ignore_for_file: type=lint`, but some warnings still appear:

Screenshot 2023-05-16 at 9 52 49 PM

@shilangyu any ideas?

**Comment by shilangyu** [comment]
> At the top of `bundled_test.dart` there's `// ignore_for_file: type=lint`, but some warnings still appear:
> Screenshot 2023-05-16 at 9 52 49 PM
> 
> @shilangyu any ideas?

This is one of a few "hardcoded" lints into the compiler, not part of standard lints (similarly to analyzer warnings for `package:meta`). So yeah, unfortunately for those you will have to add an explicit ignore_for_file

**Comment by bartekpacia** [comment]
Before merging I'll try generating this file in `.dart_tool` once again.

**Comment by bartekpacia** [comment]
> Before merging I'll try generating this file in `.dart_tool` once again.

Unfortunately, I don't have access to the Windows machine, and doing this "blindly" and verifying on CI would take hours.

Postponing for later, until someone starts to complain :)

**Review by shilangyu — APPROVED** [review]

**Pull request merged**
