### PR TITLE
add android setup documentation to readme file

### LINKED ISSUE #2346: Update Android setup documentation
### Use case

When trying to setup the example Android test I encountered an error
```
• Building apk with entrypoint test_bundle.dart...

        FAILURE: Build failed with an exception.

        * Where:
        Build file '/Users/my.user/FlutterProjects/my_project/android/build.gradle' line: 13

        * What went wrong:
        A problem occurred evaluating root project 'android'.
        > A problem occurred configuring project ':app'.
           > Removing unused resources requires unused code shrinking to be turned on. See http://d.android.com/r/tools/shrink-resources.html for more information.

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 790ms
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (1.4s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:79:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:49:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:325:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:246:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:358:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:302:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:20)
<asynchronous suspension>
#9      main (file:///Users/my.user/.pub-cache/hosted/pub.dev/patrol_cli-3.2.0/bin/main.dart:6:20)
<asynchronous suspension>
```
I was able to fix it by adding `shrinkResources false` to android/app/build.gradle, next to `minifyEnabled false`
 

### Proposal

Consider adding this piece of code to your setup documentation in the 'Pro Guard' Android section

buildTypes {
    release {
        ...
    }
    debug {
        **shrinkResources false**
        minifyEnabled false
    }
  }

### PR DESCRIPTION
**Pull request by dhirajchaurasiya10**
Fixed #2346 

I added android setup documentation to README file.

Do suggest if anything is missed.

### CODE REVIEW

**Review by piotruela — CHANGES_REQUESTED** [review]
There is already section about proguard issues in [docs](https://github.com/leancodepl/patrol/blob/7355ba9118c72682aaee818968d16492f23b858a/docs/getting-started.mdx#L176). Please update it there instead adding it to readme.

**Comment by dhirajchaurasiya10** [comment]
@piotruela updated in [docs](https://github.com/dhirajchaurasiya10/patrol/blob/master/docs/getting-started.mdx)!

**Review by piotruela — CHANGES_REQUESTED** [review]
There is already section about it in this page file. Just add `shrinkResources false` to line 186

**Review by piotruela — APPROVED** [review]
👍

**Pull request merged**
