### PR TITLE
Provide redirects for link changes from #1792" (2nd take)

### PR DESCRIPTION
**Pull request by bartekpacia**
Reverts #1812 to reintroduce #1811

Preview: https://patrol.leancode.co/~1817

### CODE REVIEW

**Comment by bartekpacia** [comment]
https://use.docs.page/frontmatter#redirect

looks like this requires us to create fake pages

**Comment by Ehesp** [comment]
Hey,

Still investigating - I believe it's due to the custom domain but I'll have a further look into this tomorrow.

**Comment by bartekpacia** [comment]
Hi @Ehesp, thank you! It's very much appreciated.

**Comment by Ehesp** [comment]
Alright think that PR should sort it... Will test it out tomorrow.

**Comment by Ehesp** [comment]
Hey just merged the fix - can you check things work as expected?

**Comment by bartekpacia** [comment]
Redirects on preview (link above) work fine. Merging and hoping for the same on main environment :)

**Pull request merged**
