### PR TITLE
Add "integrations" docs section

### PR DESCRIPTION
**Pull request by bartekpacia**

### CODE REVIEW

**Comment by fylyppo** [comment]
Maybe add also a section how to run an allure report locally in browser?

**Comment by bartekpacia** [comment]
The thing is I never did that. Can you point me to some tutorial/docs?

**Comment by fylyppo** [comment]
And if so maybe we should link also docs to how to setup Allure report? XD

**Comment by fylyppo** [comment]
https://github.com/allure-framework/allure2

**Comment by bartekpacia** [comment]
> And if so maybe we should link also docs to how to setup Allure Report? XD

Great idea. At first I just wanted this PR to be a replication of #1605 but in docs, but if there's more good we can do, let's do it.

**Review by fylyppo — APPROVED** [review]

**Pull request merged**
