### PR TITLE
Change location of generated iOS test results into `build/ios_results_$timestamp`

### PR DESCRIPTION
**Pull request by bartekpacia**
Thanks to this, the location of iOS reports will be much easier to find.

See also: #1589

### CODE REVIEW

**Comment by bartekpacia** [comment]
@fylyppo Can this break our CI workflows?

**Comment by bartekpacia** [comment]
We could also disable diagnostics to make `.xcresult`s much smaller in size: https://developer.apple.com/forums/thread/698054

**Comment by kkalisz** [comment]
Hi @bartekpacia,

Really great job, now it should be easier to find result data.
Just a few points that we don't really need action on, but still may be valid to explore.

- the name is not fixed, but it should be easy to put some regexp rules to get the correct folder.
- depending on how people were searching for test results, it may be breaking change. But taking into consideration that searching for test results was not easy and there were not a lot of issues reported to this repository regarding that, I think it should not affect most of the users.
- with a few subsequent runs we will have a few result folders, this should not be a real problem as in most cases in CI environment we will have a completely new vm instance each run, even with some specific bare metal self-hosted runners that will keep the files between runs, we can clear the folder before the tests invocation.

Regards

**Comment by bartekpacia** [comment]
Thanks for voicing your opinion @kkalisz.

I'm torn between overriding the previous test run results vs creating a new one. By default, iOS creates new directories for new test runs, and Android overrides the previous result.

At first I wanted to honor the OS default but I'm not so sure about it. Maybe it's better to always override and be consistent across platforms.

And yes, the size of iOS reports can get big :)

**Comment by bartekpacia** [comment]
FTR: #1630 which migrates our own CI workflows to new location of iOS reports.

**Comment by kkalisz** [comment]
Oh and with having multiple folders... I was mostly concerned about having a situation that we are not able to easily retrieve test results because again we have few folders. But as I said this may not be real use case and even if it is. we can just clear folders.

Having a static/predictable path is especially helpful in CI environments where you would like just to know the path (or set the path) instead of playing with regexp to retrieve the correct folder. But even with a current proposal with timestamp, it's easy enough to retrieve this path.

**Pull request merged**
