### PR TITLE
Fix entering text into SecureTextField on iOS

### LINKED ISSUE #438: Unable to interact with native password type text field in webview
Hello, i have an issue with login.
I use the package flutter_appauth which work with a webview to authenticate.
I have to fill a web form to log, enterText works with the username but not for the password, even after hiding the keyboard.
There is a placeholder with the word: Password

I tried many ways to do:
await $.native.enterText(Selector(text: 'Password'), text: '');
await $.native.enterTextByIndex('', index: 1);
Selector(field with contains ...)

Got: Patrol action failed: enterText() failed with code NOT_FOUND
And the second one says that index 1 doesn't exists.

After view hierarchy dump I got:

I did the dump and got:

```
[...
{
"AXFrame": "{{74, 372}, {227, 40}}",
"AXUniqueId": null,
"frame": {"y": 372, "x": 74, "width": 227, "height": 40},
"role_description": "text field",
"AXLabel": null,
"content_required": false,
"type": "TextField",
"title": null,
"help": "",
"custom_actions": [],
"AXValue": "Username",
"enabled": true,
"role": "AXTextField",
"subrole": null
},
{
"AXFrame": "{{74, 427}, {57, 15}}",
"AXUniqueId": null,
"frame": {"y": 427, "x": 74, "width": 57, "height": 15},
"role_description": "text",
"AXLabel": "Password",
"content_required": false,
"type": "StaticText",
"title": null,
"help": "",
"custom_actions": [],
"AXValue": "",
"enabled": true,
"role": "AXStaticText",
"subrole": null
},
{
"AXFrame": "{{74, 448}, {227, 41}}",
"AXUniqueId": null,
"frame": {"y": 448, "x": 74, "width": 227, "height": 41},
"role_description": "secure text field",
"AXLabel": null,
"content_required": false,
"type": "TextField",
"title": null,
"help": "",
"custom_actions": [],
"AXValue": "Password",
"enabled": true,
"role": "AXTextField",
"subrole": "AXSecureTextField"
},
...]
```

My tests were done using macos & iPhone simulator.
If needed I could try to take the original html from the login page and try to do something to remove confidential data.
Would you have a solution?

### PR DESCRIPTION
**Pull request by bartekpacia**
This PR:
- fixes #438

### CODE REVIEW

**Comment by bartekpacia** [comment]
The perfect solution is way harder than I thought. `NSPredicate`, I will come back!

**Comment by bartekpacia** [comment]
might be useful:
- https://stackoverflow.com/a/38055651/7009800

**Comment by bartekpacia** [comment]
this project gives me mentaln breakdowns

**Comment by bartekpacia** [comment]
https://user-images.githubusercontent.com/40357511/195790933-15cb76b6-e225-40cb-b85e-d7d062c0a446.mov

**Review by Albert221 — APPROVED** [review]

**Pull request merged**
