### PR TITLE
Create workflow for patrol integration tests on Android Emulator

### PR DESCRIPTION
**Pull request by fylyppo**

### CODE REVIEW

**Comment by fylyppo** [comment]
I want to check if jdk and gradle are pre-installed on the macos runner among the others

**Comment by bartekpacia** [comment]
You can view this info [here](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md).

**Comment by bartekpacia** [comment]
Is the purpose of this PR to fix flakiness issues on Android emulator?

**Comment by bartekpacia** [comment]
You can apply my comments after we merge this :)

**Pull request merged**
