### PR TITLE
Add example file picker screen and test

### PR DESCRIPTION
**Pull request by bartekpacia**
For @fylyppo with 💙

This test assumes that there's a file named `download.jpg` in the Downloads directory. 

https://user-images.githubusercontent.com/40357511/197803135-f1baeec1-466b-4ab8-a66f-d999cb49dd69.mov

### CODE REVIEW

**Comment by jBorkowska** [comment]
I think it is developer's responsibility to have this in mind. There is nothing we can do.

**Comment by pietraniktx** [comment]
I'm not sure about the "signaling" part of the question but I understand the problem is - "device needs to have an image in downloads folder, if not, the test will fail", right? So why can't we download the file before the test or put it there some other way programmatically?

**Comment by jBorkowska** [comment]
"We" the framework or "we" the testers? :D

**Comment by pietraniktx** [comment]
:D I belive in Bartek. And it would be nice for Patrol users to have the recipe for such scenario as it looks like quite common problem and preparing test data inside the test seems like a good practice. Cypress, for example, has a ton of recipes to help testers with cases like this, check out this one about [seeding database with node](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/server-communication__seeding-database-in-node)

**Comment by bartekpacia** [comment]
Closing so it doesn't clutter opened PRs.

**Comment by neiljaywarner** [comment]
adb screenshot or similar?

**Pull request closed without merging**
